language: java

env:
  global:
    - NEXUS_USERNAME=admin
    - secure: "QzEH8G7bzCikhOgRBMwMMI6tirhLW9jua+OXIkkPkj9dHFrJFXzrtq1aJc+slAvw9hO04CHi/RutCkFt4hE8LEs0utNbjjQEU+uyX2KX1he+RgSIVVw7Ag0rUKe/m7m8asvS4T85+dYnhPh/w2U2sth4rPMoqof7HOC3cCEV4v8="

before_script:
  - gradle clean build
  
after_success:
  - gradle uploadArchives